### PR TITLE
Runner

### LINKED ISSUE #17: New Game :Endless Runner
**Name of Game**
Endless Runner
**Description & features**
Endless Runner is an exciting, fast-paced game where you guide a chicken through an endless series of obstacles. With intuitive controls, simply click anywhere to make the chicken jump and avoid the oncoming obstacles. Test your reflexes and see how far you can go before colliding with an obstacle. Enjoy dynamic backgrounds and keep track of your score as you strive for a new high score!
**Screen Shot/ Demo video**

**Additional context**
Screenshot 2024-07-29 011217

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by priyashuu**
### 🛠️ Fixes Issue
Closes #17

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)

Screenshot 2024-07-29 011217

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
image
 lots of errors in this.

**Comment by zalabhavy** [comment]
image
 
solve this.

**Comment by priyashuu** [comment]
done sir

**Comment by priyashuu** [comment]
done sir

**Comment by zalabhavy** [comment]
fetch repository new updates.

**Pull request closed without merging**
