### PR TITLE
Added Register and login feature 

### LINKED ISSUE #5: Login/SignUp functionality
there can be a login sign up functionality so that users can login and keep a record of there played games and points

### PR DESCRIPTION
**Pull request by govindumeesala**
### 🛠️ Fixes Issue
Closes #5 

### 👨‍💻 Description
- Added Register, login and logout functionality
- Updated dashboard
- Authorized access to dashboard

### 📄 Type of Change
- [x] New feature / (Register functionality)
- [x] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
image
image
image

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by divyansh-2005** [comment]
@govindumeesala, you removed telegram user fetch logic ?
implement two types of login—Telegram-based and custom login (username and password)—here's an outline of how you can structure backend. The idea is to distinguish between a Telegram login (where the userId comes from Telegram) and a browser-based login (where users need to create an account with a username and password).

update your code and raise new pr

**Comment by govindumeesala** [comment]
@divyansh-2005 
I will raise a new pr with commented out telegram fetch user logic (Since it not yet implemented) 
Can you please, consider login or sign up with telegram id as a new issue

Thankyou

**Comment by divyansh-2005** [comment]
I am closing this pr, plz create a new pr with the required functionality

**Comment by govindumeesala** [comment]
Ok 
Will work on it @divyansh-2005

**Pull request closed without merging**
