### PR TITLE
Added arkanoid game on home page

### LINKED ISSUE #131: [FEATURE] Add Arkanoid game
**Name of Game**
Arkanoid 

**Describe the solution you'd like**
Add Arkanoid game

**Screenshots**

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
### 🛠️ Fixes Issue
Closes #131 

### 👨‍💻 Description
- Added arkanoid game

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Animation

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mehul-m-prajapati Font changed and first raw cuts that create bug

.

**Comment by mehul-m-prajapati** [comment]
@zalabhavy : This is a general bug on main branch which I listed here https://github.com/divyansh-2005/GAME_PLAYER/issues/164

**Comment by zalabhavy** [comment]
@mehul-m-prajapati I am not able to see any changes Just make new PR in that make sure update fetch updates then make PR so issue of one raw cuts solved.

**Comment by mehul-m-prajapati** [comment]
@zalabhavy : Add a new route for the game and see again #135

**Comment by mehul-m-prajapati** [comment]
@zalabhavy : thanks for your review. I have fixed this in new PR #198

**Pull request closed without merging**
