### PR TITLE
Add Game :: Rocket Boost

### LINKED ISSUE #38: NEW GAME [ ROCKET BOOST ]
### **Rocket Boost Game**

**Overview:**
Rocket Boost is a Unity-based game where players control a rocket that moves in a 3D environment along the x and y axes. The objective is to navigate from point \( p \) to point \( q \) while avoiding obstacles. Upon reaching point \( q \), players advance to the next level. If they hit an obstacle, they must replay the level.

**Game Mechanics:**
- **Movement:** Players control the rocket's movement along the x and y axes using keyboard.
- **Levels:** Each level requires the player to reach point \( q \) from point \( p \).
- **Obstacles:** Players encounter obstacles that, when hit, force them to restart the level.
- **Speed Boost (Proposed Feature):** 
  - Players can activate a temporary speed boost to enhance gameplay.
  - Visual effects such as a trail behind the rocket will indicate the boost.
  - A cooldown period will prevent continuous use of the boost.

**Screen Shot/ Demo Video:**
Game Preview

**Additional Context:**
Rocket Boost combines strategic navigation and thrilling gameplay, encouraging players to time their speed boosts effectively while avoiding obstacles. This will increase engagement and replayability as players strive to complete levels successfully.

**Check List:**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under Hacktoberfest
- [X] I follow contribution guidelines

### PR DESCRIPTION
**Pull request by KrishChothani**
### 🛠️ Fixes Issue
Closes #38 

### 👨‍💻 Description
- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.

### 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Game Preview

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by KrishChothani** [comment]
As you say , i request new PR.
and change is more than 17000+ line just because of this game is made with unity and then if we want to load this in web browser  then unity provide WEBGL file so also there is one build folder for this game.

**Comment by KrishChothani** [comment]
As you say , i request new PR.
and change is more than 17000+ line just because of this game is made with unity and then if we want to load this in web browser  then unity provide WEBGL file so also there is one build folder for this game.

**Comment by KrishChothani** [comment]
so don't  worry about 17000+ line..... It's normal

**Comment by zalabhavy** [comment]
@KrishChothani Nice works good.

Thank You for contribution.

**Pull request merged**
