### PR TITLE
ADD : new Game Reaction TIme Checker

### LINKED ISSUE #105: Reaction Time Tester
Start Screen:

Display a "Start" button to begin the game.
Gameplay:

After starting, the player waits for a random period (e.g., 2-5 seconds).
The screen changes color (or displays a specific message) to indicate that the player should react.
The player must click or tap the screen as quickly as possible after the change occurs.
Feedback:

Measure the time taken from the color change to the player’s click.
Display the reaction time to the player along with a message (e.g., "Great job!" or "Try again!").
Restart Option:

Provide an option to play again after the reaction time is displayed.
@divyansh-2005 i have implemented the game
Screenshot 2024-10-08 175643
Screenshot 2024-10-08 175650
Screenshot 2024-10-08 175655
Screenshot 2024-10-08 175706
Screenshot 2024-10-08 180210
Screenshot 2024-10-08 180330

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by RaiDevX8**
### 🛠️ Fixes Issue
Closes #105

### 👨‍💻 Description
The Reaction Time Checker game challenges players to test their reflexes by clicking a button as soon as a signal appears. Players wait for a prompt that transitions from a red "waiting" state to a green "click now" state, measuring their response time in milliseconds. The game aims to provide a fun and engaging way to gauge how quickly users can react, with instant feedback on their performance.

### 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Screenshot 2024-10-08 175643
Screenshot 2024-10-08 175650
Screenshot 2024-10-08 175655
Screenshot 2024-10-08 175706
Screenshot 2024-10-08 180210
Screenshot 2024-10-08 180330

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [ ] This PR is submitted under the GSSoC program.
- [ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by RaiDevX8** [comment]
@divyansh-2005

**Comment by RaiDevX8** [comment]
@divyansh-2005

**Comment by RaiDevX8** [comment]
@zalabhavy bro its been a week no reviews fo far

**Comment by zalabhavy** [comment]
image


Errors.

**Comment by RaiDevX8** [comment]
Let me check

**Comment by RaiDevX8** [comment]
@zalabhavy updated the branch it has some merge conflicts and i fixed it

**Pull request merged**
