### PR TITLE
Added favicon for this website

### LINKED ISSUE #138: add fevicon to the website
we can add fevicon to the website

### PR DESCRIPTION
**Pull request by fahadshahbaz**
### 🛠️ Fixes Issue
Closes #138

### 👨‍💻 Description
- Updated the favicon to a new custom logo.
- Replaced the default vite icon with new one.
- This enhances branding and improves recognition in browser tabs.

### 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
image

### ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [ ] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [ ] This PR is submitted under the GSSoC program.
- [ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
@fahadshahbaz channges in pacakge.json files correct it and make new PR.

**Comment by zalabhavy** [comment]
Update your repository to fetches new updates and then make new PR

**Comment by fahadshahbaz** [comment]
@zalabhavy The package.json file is up to date. I'm waiting for your review.

**Comment by zalabhavy** [comment]
@fahadshahbaz Works perfect but please fetch updates because i just merged pull request so that changes not visible when i merge this.

**Comment by fahadshahbaz** [comment]
@zalabhavy Everything is working fine on my end. If the issue still persists, could you please elaborate more on what you’re referring to? Thanks!

**Pull request merged**
