### PR TITLE
feat : Redesigned the Contact Page and migrated to Tailwind CSS

### LINKED ISSUE #309: [FEATURE]:Contact Us Page Redesign
**Is your feature request related to a problem? Please describe.**  
The **Contact Page* currently has several design flaws that negatively impact the user experience. It is not responsive, making it difficult to view on various screen sizes. Additionally, the overall UI/UX design is lacking, with poor visual structure, making the content hard to engage with.

**Describe the solution you'd like**  
A full redesign of the **Contact Page** is needed to address the responsiveness issues and improve the overall UI/UX. The page should adapt smoothly to different screen sizes, with a modern and user-friendly design that improves readability and navigability. Implementing better spacing, typography, and an appealing layout would significantly enhance the page's usability.

**Screenshots**  
image

**Screenshots/video of feature**  
### Sample
image

**Checklist**  
- [X] I am contributing under GSSoC-ext  
- [X] I am contributing under Hacktoberfest  
- [X] I follow contribution guidelines

### PR DESCRIPTION
**Pull request by laxmanp090404**
### 🛠️ Fixes Issue
Closes #309 
### 👨‍💻 Description
- **Redesigned the Contact Page**: The Contact Page has been updated with a fresh look, utilizing Tailwind CSS for responsive and efficient styling.
- **Flexbox Layout Improvements**: Adjusted the layout so that the left section now grows dynamically based on the content of the right section, ensuring a cohesive design across devices.
- **Enhanced User Experience**: The new design improves usability by making the contact form more visually appealing and easier to navigate. The form inputs, including name, email, and message fields, now align perfectly across different screen sizes.
- **Modern CSS Techniques**: Migrated from legacy CSS to Tailwind CSS, which simplifies styling and ensures better performance and maintainability.

### 📄 Type of Change
- [x] New feature (non-breaking change which adds functionality)

### 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/5d919349-ce97-402d-87ee-5d09e660897b

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by laxmanp090404** [comment]
@divyansh-2005  Please review and merge sir.
Thank You,

**Comment by laxmanp090404** [comment]
@zalabhavy  Please review and merge Sir.
Thank You.

**Comment by zalabhavy** [comment]
image

This is not looks good.

**Comment by laxmanp090404** [comment]
@zalabhavy  Ok I will update .

**Comment by laxmanp090404** [comment]
@zalabhavy  sure .Working on the improvement Sir.

**Comment by laxmanp090404** [comment]
@zalabhavy  Check on now pls merge my PR.

Video:

https://github.com/user-attachments/assets/38b8f274-c5cb-4ee3-94eb-b7fc355e659d

**Comment by laxmanp090404** [comment]
PS:
I have solved the button overlay issue.

## Video:

https://github.com/user-attachments/assets/fd46757e-950a-4d0c-aa2c-6d8536ff6bee

**Comment by laxmanp090404** [comment]
PS: I have solved the button layover issue. Attached the demo. @zalabhavy 
## Demo:
https://github.com/user-attachments/assets/465670a4-9d38-4182-a225-988154892050

**Comment by laxmanp090404** [comment]
@zalabhavy Please review and merge PR. Is there anything I can do for facilitating merge.

**Comment by zalabhavy** [comment]
image
 solve overlapping and fetch repository because i merge some other prs.

**Comment by laxmanp090404** [comment]
@zalabhavy  Solved issue please check.

**Comment by laxmanp090404** [comment]
@zalabhavy  Is there anything I can do.Please merge my PR.
Thanks

**Comment by zalabhavy** [comment]
@laxmanp090404 Create new PR after fetching so it will better to review me

Thank You !

**Comment by laxmanp090404** [comment]
@zalabhavy  As instructed I have opened a new Pull request #398 . Please look into it and merge it.

**Pull request closed without merging**
