### PR TITLE
added endless runner

### LINKED ISSUE #17: New Game :Endless Runner
**Name of Game**
Endless Runner
**Description & features**
Endless Runner is an exciting, fast-paced game where you guide a chicken through an endless series of obstacles. With intuitive controls, simply click anywhere to make the chicken jump and avoid the oncoming obstacles. Test your reflexes and see how far you can go before colliding with an obstacle. Enjoy dynamic backgrounds and keep track of your score as you strive for a new high score!
**Screen Shot/ Demo video**

**Additional context**
Screenshot 2024-07-29 011217

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by priyashuu**
### 🛠️ Fixes Issue
Closes #17 

### 👨‍💻 Description

Game logic and basic description
An Endless Runner game where you control a character running through an ever-changing environment. The goal is to survive as long as possible by avoiding obstacles, collecting power-ups, and achieving high scores.

Point down the features
Game points

Dynamic Environment:
Unique, procedurally generated levels each run.

Character Control:
Smooth controls for jumping, sliding, and dodging.
Unlockable characters with unique abilities.

Scoring and Achievements:
Score based on distance and collectibles.

Visual and Audio Design:
High-quality graphics and animations.

User Interface:
Intuitive controls and HUD displaying score and distance.

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Include screenshots or GIFs to demonstrate your changes
Screenshot 2024-07-29 011217

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
@priyashuu fix my-project/package-lock.json it has lots of changes.

**Comment by zalabhavy** [comment]
@priyashuu Please resolve conflicts.

**Comment by priyashuu** [comment]
image
how to resolve this , there is so much conflict , please help me to resolve this , i need your help

**Comment by priyashuu** [comment]
done sir

**Comment by priyashuu** [comment]
dear @zalabhavy I wanted to kindly follow up on my pull request, which has been pending for the past 4 days. Could you please merge it when you get a chance? It would really help me to continue with the next steps.

**Comment by priyashuu** [comment]
ok ill update my pr  asap

**Pull request closed without merging**
