### PR TITLE
Add Checkers Game

### LINKED ISSUE #240: Add Checkers
**Name of Game**
Checkers

**Description & features**
A two-player board game where players move pieces diagonally across a board with the goal of capturing the opponent’s pieces.

**check list**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under hacktoberfest
- [X] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by haseebzaki-07**
### 🛠️ Fixes Issue
Closes #240 

### 👨‍💻 Description
This PR add checkers game to the my-projects folder of the repo
A two-player board game where players move pieces diagonally across a board with the goal of capturing the opponent’s pieces

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Screenshot 2024-10-16 230620

### ✅ Checklist
- [X] I am a participant of GSSoC-ext.
- [X] I have followed the contribution guidelines of this project.
- [X] I have viewed deployment of my code.
- [X] My changes generate no new warnings.
- [X] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [X] This PR is submitted under the GSSoC program.
- [X] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
image
 

Errors.

**Comment by haseebzaki-07** [comment]
Hey @zalabhavy I resolved the errors please check!

**Comment by zalabhavy** [comment]
Error.

**Comment by haseebzaki-07** [comment]
@zalabhavy where is the error

**Comment by zalabhavy** [comment]
@haseebzaki-07 Home page  deleted in this PR make PR again.
image

**Pull request closed without merging**
