### PR TITLE
Add Sudoku game

### LINKED ISSUE #169: Add Sudoku
**Name of Game**
Sudoku Game

**Description & Features**
The project needs to add a classic Sudoku game with the following features:
- A 9x9 grid with predefined puzzles of varying difficulty levels (easy, medium, hard).
- Functionality to fill in numbers, check for mistakes, and reset the board.
- Implement a timer to track how long it takes to complete a puzzle.
- Include a hint system that helps the player when stuck.
- Option to generate new random puzzles or load predefined ones.

**Screen Shot/ Demo video**
image

**Check List**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under Hacktoberfest
- [x] I follow the contribution guidelines

### PR DESCRIPTION
**Pull request by rudrapratap63**
### 🛠️ Fixes Issue
Closes #169 

### 👨‍💻 Description
The project needs to add a classic Sudoku game with the following features:
- A 9x9 grid with predefined puzzles of varying difficulty levels (easy, medium, hard).
- Functionality to fill in numbers, check for mistakes, and reset the board.
- Implement a timer to track how long it takes to complete a puzzle.
- Include a hint system that helps the player when stuck.
- Option to generate new random puzzles or load predefined ones.

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/0976a5ec-baf2-42e4-b1b6-94e979d97db5

image

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
@rudrapratap63 check your code view of game cards changed.

image

**Comment by rudrapratap63** [comment]
@zalabhavy Ok, sir, I will fix this.

**Comment by rudrapratap63** [comment]
Hello @zalabhavy  , I checked the code, and the game card is the same as before; there haven't been any changes.

**Comment by rudrapratap63** [comment]
@divyansh-2005 @zalabhavy i resolved the conflict . please check the pr

**Comment by zalabhavy** [comment]
image

not 4 cards in one raw

**Comment by zalabhavy** [comment]
@rudrapratap63 I need 4 Cards in one raw in your every PR there are 3 cards in one raw.

**Comment by rudrapratap63** [comment]
@zalabhavy okk sir i wil fix this and update the all pr's today

**Comment by rudrapratap63** [comment]
@zalabhavy now fix the card problem :- 

image

image

**Comment by rudrapratap63** [comment]
@zalabhavy sir check my all pr i resolve the issue

**Pull request merged**
