### PR TITLE
add new game,  name:: rocket boost, which based on webGl, made with u…

### LINKED ISSUE #38: NEW GAME [ ROCKET BOOST ]
### **Rocket Boost Game**

**Overview:**
Rocket Boost is a Unity-based game where players control a rocket that moves in a 3D environment along the x and y axes. The objective is to navigate from point \( p \) to point \( q \) while avoiding obstacles. Upon reaching point \( q \), players advance to the next level. If they hit an obstacle, they must replay the level.

**Game Mechanics:**
- **Movement:** Players control the rocket's movement along the x and y axes using keyboard.
- **Levels:** Each level requires the player to reach point \( q \) from point \( p \).
- **Obstacles:** Players encounter obstacles that, when hit, force them to restart the level.
- **Speed Boost (Proposed Feature):** 
  - Players can activate a temporary speed boost to enhance gameplay.
  - Visual effects such as a trail behind the rocket will indicate the boost.
  - A cooldown period will prevent continuous use of the boost.

**Screen Shot/ Demo Video:**
Game Preview

**Additional Context:**
Rocket Boost combines strategic navigation and thrilling gameplay, encouraging players to time their speed boosts effectively while avoiding obstacles. This will increase engagement and replayability as players strive to complete levels successfully.

**Check List:**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under Hacktoberfest
- [X] I follow contribution guidelines

### PR DESCRIPTION
**Pull request by KrishChothani**
…nity

### 🛠️ Fixes Issue
Closes #38 

### 👨‍💻 Description
- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.

### 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Game Preview

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
@KrishChothani In this PR issue number is not mention please provide that and resolve conflicts.

Thank You !

**Comment by KrishChothani** [comment]
#38

**Comment by zalabhavy** [comment]
Please Resolve conflicts

**Review by divyansh-2005 — CHANGES_REQUESTED** [review]
why there are files are added in public/Build ?

**Comment by KrishChothani** [comment]
This game is made with unity, and for Webgl it give you Build folder which i want to place in public,

**Comment by divyansh-2005** [comment]
ok, resolve conflicts

**Comment by KrishChothani** [comment]
I resolve all conflicts.

**Comment by zalabhavy** [comment]
@KrishChothani My friend how I am explain you ? First You are now fetched updates then also make changes of line 17k+.

Take Your time learn how to create pull request that is common mistake also made by me.

You can create new PR I am closing this PR.

Thank You !

**Pull request closed without merging**
