### PR TITLE
Ballshooting Issue no -#19

### LINKED ISSUE #19: Ball Shooting Game
**Name of Game**
Ball Shooting Game

**Description & features**
A Simple Game where balls will come to you from every direction and you have to shoot them if them touch you game will be over

**Screen Shot/ Demo video**
Screenshot 2024-10-03 012944

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by 17arindam**
### 🛠️ Fixes Issue
Closes #19 

### 👨‍💻 Description
-added ball shooting game where you shoot incoming balls to increase your score
-the game is added to gamelist
-the game is responsive

### 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x]Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Screenshot 2024-10-04 215607
Screenshot 2024-10-04 221142
Screenshot 2024-10-04 221157

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by 17arindam** [comment]
@divyansh-2005 please review my pr i have implemented the game

**Comment by zalabhavy** [comment]
@17arindam pakage.json and pakage-lock.json file changed fix it.

**Comment by 17arindam** [comment]
@zalabhavy  actually the changes in package.json and package-lock.json is due to library i used gsap if i delete it gsap will not be installed directly when we do npm i . but if you still want then let me know

**Comment by zalabhavy** [comment]
@17arindam ok then remove changes in **my-project/package-lock.json**

**Comment by 17arindam** [comment]
@zalabhavy deleted my-project/package-lock.json file

**Comment by zalabhavy** [comment]
@17arindam  can you please resolve conflicts.

**Comment by 17arindam** [comment]
@zalabhavy resolved conflicts

**Review by divyansh-2005 — CHANGES_REQUESTED** [review]
score is showing above navbar fix that and resolve conflicts

**Comment by 17arindam** [comment]
@divyansh-2005 i have resolved the score issue and the other problem it was showing was because of wrong tetris game path and the tetris game is not added to game section can i raise a issue for that?

**Comment by 17arindam** [comment]
@zalabhavy is there any issue needs to be addressed

**Comment by 17arindam** [comment]
@zalabhavy is there still any issue ?

**Comment by 17arindam** [comment]
@divyansh-2005 @zalabhavy please review my pr

**Pull request closed without merging**
