### PR TITLE
Improvement Responsiveness and Structure all game as Same Formate.

### LINKED ISSUE #39: [FEATURE --- Improve Responsiveness]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the website is not responsive, making it difficult for users to navigate and access content on different devices. Elements may overlap or be misaligned, impacting the overall user experience.

**Describe the solution you'd like**
I would like the website to be fully responsive, ensuring that all elements scale properly across various screen sizes and orientations. This may involve using CSS media queries and flexible layouts to enhance usability on mobile and desktop devices.

**Screenshots**
*(Attach relevant screenshots that showcase the current issues with responsiveness on the website.)*

**Screenshots/Video of Feature**
*(Include any screenshots or a demo video showcasing how improved responsiveness would enhance user experience.)*

**Check List:**
- [ ] I am contributing under GSSoC-ext
- [ ] I am contributing under Hacktoberfest
- [ ] I follow contribution guidelines

### PR DESCRIPTION
**Pull request by KrishChothani**
### 🛠️ Fixes Issue
Closes #39

### [ include :: Every  Games ]
- Done Responsive Website 
- Make it Beautiful
- Create Same Game Structure in all games
- Change UI design in All Games

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by KrishChothani** [comment]
As you said "According to your work"
I request you to give good level

**Comment by zalabhavy** [comment]
@KrishChothani Resolve conflicts.

**Comment by KrishChothani** [comment]
I resolve all conflict

**Comment by KrishChothani** [comment]
please if this done ... then also close #290 which is also added in this .... and give PR for Both

**Comment by KrishChothani** [comment]
@zalabhavy 
please merged this PR first so there is no generated any other conflict.
And also in this pr, I include issue #290 ... so you can close this and give both this [ #39 ] and [ #290 ] 
because this was added in this ...
and give both PR.

**Comment by KrishChothani** [comment]
@zalabhavy 
I request you to please add this first.
just because I work on two issues and some small conflicts i need change all things for both.

**Comment by KrishChothani** [comment]
And also give good level

**Comment by KrishChothani** [comment]
And if there is any other issue from this.. 
just comment it ...
I will fix it within 1 hour

**Comment by zalabhavy** [comment]
Error.

**Comment by KrishChothani** [comment]
done

**Comment by zalabhavy** [comment]
image

Toggle option not available and also for some game responsive is not good i think you are using chatgpt there are many changes that are not needed.

**Pull request closed without merging**
