### PR TITLE
Implemented AI Chatbot

### LINKED ISSUE #179: [FEATURE] Add Chatbot
I want to implement a chatbot for the website.

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by NK-Works**
### 🛠️ Fixes Issue
Closes #179 

### 👨‍💻 Description
- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
image
This is the AI Chatbot

**NOTE**
This chatbot symbol will only appear after you place your chatbot id generated fromt he chatbase.co and place it here...
then the chat icon will automatically activate and be visible.
image
Place the ChatID here

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
image

Not able to see.

**Comment by NK-Works** [comment]
you need to put the chatbot id after creating it from the webstie www.chatbase.co
once the id is put the chatbot icon will appear

**Comment by zalabhavy** [comment]
@NK-Works You can put that chatbot id ?

**Comment by NK-Works** [comment]
@zalabhavy well putting personal env variables here? Doesn't feel right u know...
U r the owner of the project create one a put the id here

**Comment by govindumeesala** [comment]
@zalabhavy  Hey, I actually raised issue for integrating a chatbot first, the issue is #47 .
I even also raised the pr for that issue #214 first.

As first come , first serve is followed int GSSoC
Kindly consider checking out my pr for chatbot integration #214

**Comment by NK-Works** [comment]
@zalabhavy @divyansh-2005  If there are any issues I can show u the steps to create and train the chatbot with just putting the website link and the about page as text to the chatbot interface if you want but i can't provide you my personal chatbot id as i dont have a pro account and can only create 1 chatbot at a time...
So for contributing to other repos i need that...
but it just takes 3 mins literally to train you own chatbot in that website using just the link to your website (game_player) to train the bot... so dont worry and also just message me here I will give u a guide to make your own using screenshots... :)
Hope that works:)

**Comment by NK-Works** [comment]
@divyansh-2005 any updates here...
please merge the pr

**Comment by NK-Works** [comment]
@divyansh-2005 any updates of the PR been 3 weeks

**Comment by NK-Works** [comment]
@zalabhavy @divyansh-2005 @govindumeesala @KrishChothani only 2 days remains would really appreciate if you merge my pr

**Comment by NK-Works** [comment]
@zalabhavy @divyansh-2005 @govindumeesala @KrishChothani  please merge the pr as only a day remains in the GSSOC...
At this its a request please dont let my work go waste 🙏

**Pull request closed without merging**
