### PR TITLE
Math quiz

### LINKED ISSUE #210: Math quiz game
**Name of Game**
Math quiz game

**Description & features**
Description: A basic math quiz game that generates random math questions (like addition, subtraction, multiplication) and provides multiple-choice answers for the player to choose from.
#### Key Concepts:
- Random number generation for questions.
- State management for correct/incorrect answers and score tracking.
- Timer for added difficulty.

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

@zalabhavy  please assign me this

### PR DESCRIPTION
**Pull request by govindumeesala**
### 🛠️ Fixes Issue
Closes #210 

### 👨‍💻 Description
Math Quiz game with a broader range of math questions including addition, subtraction, multiplication, division, and even questions with powers (exponentiation) and modulus operations.

#### Features:
** Enhanced Question Variety: includes: **
- Addition (+)
- Subtraction (-)
- Multiplication (*)
- Division (/, rounded to two decimal places)
- Exponentiation (^)
- Modulus (%)
- Dynamic Answer Choices: The correct answer is mixed with a few random incorrect answers to form multiple-choice options.

- Score Tracking, Timer, and Game Over: Same as before, but with enhanced questions.

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
image
image

### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

@zalabhavy  please check this out

### CODE REVIEW

**Comment by zalabhavy** [comment]
@govindumeesala Fetch updates.

**Comment by govindumeesala** [comment]
@zalabhavy  i have fetched the updates. Please check out now

**Comment by zalabhavy** [comment]
Errors.

**Comment by govindumeesala** [comment]
> Errors.

Resolved errors please checkout now

**Comment by govindumeesala** [comment]
i am closing this, because of errors and raising new pr

**Pull request closed without merging**
