### PR TITLE
Add memory card game

### LINKED ISSUE #239: Add Memory card game
**Name of Game**
Memory Card Game

**Description & features**
A game where players flip over two cards at a time, trying to find matching pairs. The game continues until all pairs are found.

**check list**
- [X] I am contributing under GSSoC-ext
- [X] I am contributing under hacktoberfest
- [X] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by haseebzaki-07**
### 🛠️ Fixes Issue
closes #239 

### 👨‍💻 Description

This PR adds memory card game to my-projects folder of the repo
A game where players flip over two cards at a time, trying to find matching pairs. The game continues until all pairs are found.

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/28180af6-d6c3-4aa8-a990-55d40678168a

### ✅ Checklist
- [X] I am a participant of GSSoC-ext.
- [X] I have followed the contribution guidelines of this project.
- [X] I have viewed deployment of my code.
- [X] My changes generate no new warnings.
- [X] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [X] This PR is submitted under the GSSoC program.
- [X] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by zalabhavy** [comment]
image


Errors

**Comment by haseebzaki-07** [comment]
hey @zalabhavy please check!

**Comment by haseebzaki-07** [comment]
hey @zalabhavy please check this PR

**Comment by zalabhavy** [comment]
image


Error

**Comment by haseebzaki-07** [comment]
hey @zalabhavy please check this

**Comment by zalabhavy** [comment]
image


Issue.

**Pull request closed without merging**
